# Generated by Django 5.2.5 on 2025-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('kc_inicial', models.FloatField()),
                ('kc_medio', models.FloatField()),
                ('kc_final', models.FloatField()),
                ('z_min', models.FloatField()),
                ('z_max', models.FloatField()),
                ('p', models.FloatField()),
            ],
        ),
    ]
