# Generated by Django 5.2.5 on 2025-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='kc_final',
            field=models.FloatField(verbose_name='Kc Final'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='kc_inicial',
            field=models.FloatField(verbose_name='Kc Inicial'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='kc_medio',
            field=models.FloatField(verbose_name='Kc Médio'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Cultura'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='p',
            field=models.FloatField(verbose_name='Fator de depleção (-)'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='z_max',
            field=models.FloatField(verbose_name='Z Max (m)'),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='z_min',
            field=models.FloatField(verbose_name='Z Min (m)'),
        ),
    ]
