# Generated by Django 5.2.5 on 2025-08-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturas', '0002_alter_cultura_kc_final_alter_cultura_kc_inicial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultura',
            options={'ordering': ['nome'], 'verbose_name': 'Cultura', 'verbose_name_plural': 'Culturas'},
        ),
    ]
