# Generated by Django 5.2.5 on 2025-08-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('capacidade_campo', models.FloatField()),
                ('ponto_murcha', models.FloatField()),
                ('densidade', models.FloatField()),
                ('condutividade_hidraulica', models.FloatField()),
            ],
        ),
    ]
