# Generated by Django 5.2.5 on 2025-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0002_solo_data_cadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solo',
            options={'verbose_name': 'Solo', 'verbose_name_plural': 'Solos'},
        ),
        migrations.AlterField(
            model_name='solo',
            name='capacidade_campo',
            field=models.FloatField(verbose_name='Capacidade de Campo (%)'),
        ),
        migrations.AlterField(
            model_name='solo',
            name='condutividade_hidraulica',
            field=models.FloatField(verbose_name='Condutividade Hidráulica (cm/h)'),
        ),
        migrations.AlterField(
            model_name='solo',
            name='densidade',
            field=models.FloatField(verbose_name='Densidade do Solo (g/cm³)'),
        ),
        migrations.AlterField(
            model_name='solo',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='solo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Solo'),
        ),
        migrations.AlterField(
            model_name='solo',
            name='ponto_murcha',
            field=models.FloatField(verbose_name='Ponto de Murcha Permanente (%)'),
        ),
    ]
